name: CI - Tech Challenge

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Build e testes
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_fiap

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d blog_fiap"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: blog_fiap
      PORT: 4000
      NODE_ENV: test

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Compilar TypeScript
        run: npm run build

      - name: Executar testes e cobertura
        run: npm run test:coverage